#pragma once

// From glfw3.h
#define LLAMA_MOUSE_BUTTON_1         0
#define LLAMA_MOUSE_BUTTON_2         1
#define LLAMA_MOUSE_BUTTON_3         2
#define LLAMA_MOUSE_BUTTON_4         3
#define LLAMA_MOUSE_BUTTON_5         4
#define LLAMA_MOUSE_BUTTON_6         5
#define LLAMA_MOUSE_BUTTON_7         6
#define LLAMA_MOUSE_BUTTON_8         7
#define LLAMA_MOUSE_BUTTON_LAST      LLAMA_MOUSE_BUTTON_8
#define LLAMA_MOUSE_BUTTON_LEFT      LLAMA_MOUSE_BUTTON_1
#define LLAMA_MOUSE_BUTTON_RIGHT     LLAMA_MOUSE_BUTTON_2
#define LLAMA_MOUSE_BUTTON_MIDDLE    LLAMA_MOUSE_BUTTON_3
